"""Conversion between Python dataclasses and wasmtime-py runtime types.

GENERATOR-NOTE: All to_wasm_* and from_wasm_* functions in this file will be
auto-generated by witgen. The function signatures are the stable contract.

wasmtime-py v40 type mapping (from spike_variants.py findings):
- Records: Record() with kebab-case __dict__ attrs
- Variants (tagged): Variant(tag="case-name", payload=...)
- Enums: plain str
- result<record, string>: untagged -> Record for Ok, str for Err
- result<string, string>: tagged -> Variant("ok"/"err", str)
- result<_, string>: untagged -> None for Ok, str for Err
- option<T>: None / value
"""

from __future__ import annotations

from typing import Any

# FIXME(wasmtime-py): v40 does not export Record/Variant from a public path;
# wasmtime.component._types is the only way to access them.  Revisit when
# wasmtime-py exposes a public API for component-model types.
from wasmtime.component._types import Record, Variant

from ._types import (
    AllowedBotConfig,
    AllowEmailValidationConfig,
    BotConfig,
    BotResult,
    DeniedBotConfig,
    DenyEmailValidationConfig,
    DetectedSensitiveInfoEntity,
    EmailValidationConfig,
    EmailValidationResult,
    Err,
    FilterResult,
    Ok,
    Result,
    SensitiveInfoConfig,
    SensitiveInfoEntities,
    SensitiveInfoEntitiesAllow,
    SensitiveInfoEntitiesDeny,
    SensitiveInfoEntity,
    SensitiveInfoEntityCreditCardNumber,
    SensitiveInfoEntityCustom,
    SensitiveInfoEntityEmail,
    SensitiveInfoEntityIpAddress,
    SensitiveInfoEntityPhoneNumber,
    SensitiveInfoResult,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _rec(**kwargs: Any) -> Record:
    """Build a wasmtime Record with kebab-case attributes.

    FIXME(wasmtime-py): v40 has no public constructor for Records with initial
    values; the only way to set fields is via direct ``__dict__`` mutation.
    Revisit when wasmtime-py adds a proper Record builder API.
    """
    r = Record()
    r.__dict__.update(kwargs)
    return r


# ---------------------------------------------------------------------------
# to_wasm: Python -> wasmtime
# ---------------------------------------------------------------------------


def to_wasm_bot_config(config: BotConfig) -> Variant:
    """Convert BotConfig union to a wasmtime Variant."""
    if isinstance(config, AllowedBotConfig):
        return Variant(
            "allowed-bot-config",
            _rec(
                entities=config.entities,
                **{"skip-custom-detect": config.skip_custom_detect},
            ),
        )
    return Variant(
        "denied-bot-config",
        _rec(
            entities=config.entities,
            **{"skip-custom-detect": config.skip_custom_detect},
        ),
    )


def to_wasm_email_validation_config(config: EmailValidationConfig) -> Variant:
    """Convert EmailValidationConfig union to a wasmtime Variant."""
    if isinstance(config, AllowEmailValidationConfig):
        return Variant(
            "allow-email-validation-config",
            _rec(
                **{
                    "require-top-level-domain": config.require_top_level_domain,
                    "allow-domain-literal": config.allow_domain_literal,
                },
                allow=config.allow,
            ),
        )
    return Variant(
        "deny-email-validation-config",
        _rec(
            **{
                "require-top-level-domain": config.require_top_level_domain,
                "allow-domain-literal": config.allow_domain_literal,
            },
            deny=config.deny,
        ),
    )


def to_wasm_sensitive_info_entity(entity: SensitiveInfoEntity) -> Variant:
    """Convert a SensitiveInfoEntity to a wasmtime Variant."""
    if isinstance(entity, SensitiveInfoEntityEmail):
        return Variant("email")
    if isinstance(entity, SensitiveInfoEntityPhoneNumber):
        return Variant("phone-number")
    if isinstance(entity, SensitiveInfoEntityIpAddress):
        return Variant("ip-address")
    if isinstance(entity, SensitiveInfoEntityCreditCardNumber):
        return Variant("credit-card-number")
    return Variant("custom", entity.value)


def to_wasm_sensitive_info_entities(entities: SensitiveInfoEntities) -> Variant:
    """Convert SensitiveInfoEntities union to a wasmtime Variant."""
    items = [to_wasm_sensitive_info_entity(e) for e in entities.entities]
    if isinstance(entities, SensitiveInfoEntitiesAllow):
        return Variant("allow", items)
    return Variant("deny", items)


def to_wasm_sensitive_info_config(config: SensitiveInfoConfig) -> Record:
    """Convert SensitiveInfoConfig to a wasmtime Record."""
    return _rec(
        entities=to_wasm_sensitive_info_entities(config.entities),
        **{
            "context-window-size": config.context_window_size,
            "skip-custom-detect": config.skip_custom_detect,
        },
    )


# ---------------------------------------------------------------------------
# from_wasm: wasmtime -> Python
# ---------------------------------------------------------------------------


def from_wasm_filter_result(raw: Any) -> Result[FilterResult, str]:
    """Convert match-filters result (untagged: Record=Ok, str=Err)."""
    if isinstance(raw, str):
        return Err(raw)
    return Ok(
        FilterResult(
            allowed=raw.allowed,
            matched_expressions=getattr(raw, "matched-expressions"),
            undetermined_expressions=getattr(raw, "undetermined-expressions"),
        )
    )


def from_wasm_bot_result(raw: Any) -> Result[BotResult, str]:
    """Convert detect-bot result (untagged: Record=Ok, str=Err)."""
    if isinstance(raw, str):
        return Err(raw)
    return Ok(
        BotResult(
            allowed=raw.allowed,
            denied=raw.denied,
            verified=raw.verified,
            spoofed=raw.spoofed,
        )
    )


def from_wasm_fingerprint_result(raw: Any) -> Result[str, str]:
    """Convert generate-fingerprint result (tagged: Variant("ok"/"err", str))."""
    if not isinstance(raw, Variant):
        raise TypeError(f"expected Variant from generate-fingerprint, got {type(raw)}")
    if not isinstance(raw.payload, str):
        raise TypeError(
            f"expected str payload in fingerprint result, got {type(raw.payload)}"
        )
    if raw.tag == "ok":
        return Ok(raw.payload)
    return Err(raw.payload)


def from_wasm_validate_characteristics_result(raw: Any) -> Result[None, str]:
    """Convert validate-characteristics result (untagged: None=Ok, str=Err)."""
    if raw is None:
        return Ok(None)
    return Err(raw)


def from_wasm_email_validation_result(
    raw: Any,
) -> Result[EmailValidationResult, str]:
    """Convert is-valid-email result (untagged: Record=Ok, str=Err)."""
    if isinstance(raw, str):
        return Err(raw)
    return Ok(
        EmailValidationResult(
            validity=getattr(raw, "validity"),
            blocked=getattr(raw, "blocked"),
        )
    )


def from_wasm_sensitive_info_entity(raw: Any) -> SensitiveInfoEntity:
    """Convert a wasmtime Variant to SensitiveInfoEntity."""
    if not isinstance(raw, Variant):
        raise TypeError(f"expected Variant for sensitive-info-entity, got {type(raw)}")
    tag = raw.tag
    if tag == "email":
        return SensitiveInfoEntityEmail()
    if tag == "phone-number":
        return SensitiveInfoEntityPhoneNumber()
    if tag == "ip-address":
        return SensitiveInfoEntityIpAddress()
    if tag == "credit-card-number":
        return SensitiveInfoEntityCreditCardNumber()
    if tag == "custom":
        if not isinstance(raw.payload, str):
            raise TypeError(
                f"expected str payload for custom entity, got {type(raw.payload)}"
            )
        return SensitiveInfoEntityCustom(raw.payload)
    raise ValueError(f"Unknown sensitive-info-entity tag: {tag}")


def from_wasm_detected_entity(raw: Any) -> DetectedSensitiveInfoEntity:
    """Convert a wasmtime Record to DetectedSensitiveInfoEntity."""
    return DetectedSensitiveInfoEntity(
        start=raw.start,
        end=raw.end,
        identified_type=from_wasm_sensitive_info_entity(
            getattr(raw, "identified-type")
        ),
    )


def from_wasm_sensitive_info_result(raw: Any) -> SensitiveInfoResult:
    """Convert detect-sensitive-info result (direct Record, no result wrapper)."""
    return SensitiveInfoResult(
        allowed=[from_wasm_detected_entity(e) for e in getattr(raw, "allowed")],
        denied=[from_wasm_detected_entity(e) for e in getattr(raw, "denied")],
    )
