# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class FilterResult:
    allowed: bool
    matched_expressions: List[str]
    undetermined_expressions: List[str]


class WitWorld(Protocol):

    @abstractmethod
    def match_filters(self, request: str, expressions: List[str], allow_if_match: bool) -> FilterResult:
        """
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError

