"""Code generation: IR → Python source files."""

from __future__ import annotations

from .ir import (
    WitEnum,
    WitFunc,
    WitInterface,
    WitList,
    WitOption,
    WitPrimitive,
    WitRecord,
    WitRef,
    WitResult,
    WitType,
    WitTypeAlias,
    WitTypeDef,
    WitVariant,
    WitVariantCase,
    WitWorld,
)
from .naming import kebab_to_pascal, kebab_to_snake, variant_case_class_name

GENERATED_HEADER = '''\
"""GENERATED by witgen — DO NOT EDIT.

Re-generate with: uv run python -m tools.witgen
"""
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_unit_variant_case(case: WitVariantCase) -> bool:
    return case.payload is None


def _is_named_record_ref(ty: WitType) -> bool:
    """True if the type is a reference to a named record."""
    return isinstance(ty, WitRef)


def _variant_has_overlapping_record_cases(
    variant: WitVariant, type_map: dict[str, WitTypeDef]
) -> bool:
    """Check if all variant cases reference distinct named records."""
    for case in variant.cases:
        if case.payload is None:
            return False
        if not isinstance(case.payload, WitRef):
            return False
        referred = type_map.get(case.payload.name)
        if not isinstance(referred, WitRecord):
            return False
    return True


def _resolve_type(ty: WitType, type_map: dict[str, WitTypeDef]) -> WitType:
    """Resolve type aliases."""
    if isinstance(ty, WitRef):
        defn = type_map.get(ty.name)
        if isinstance(defn, WitTypeAlias):
            return _resolve_type(defn.target, type_map)
    return ty


def _build_type_map(world: WitWorld) -> dict[str, WitTypeDef]:
    """Build name→definition map from world types + imported types."""
    m: dict[str, WitTypeDef] = {}
    for t in world.types:
        m[t.name] = t
    for imp in world.imports:
        for t in imp.types:
            m[t.name] = t
    return m


def _py_type_annotation(
    ty: WitType,
    type_map: dict[str, WitTypeDef],
) -> str:
    """Generate a Python type annotation for a WIT type."""
    ty = _resolve_type(ty, type_map)
    if isinstance(ty, WitPrimitive):
        if ty.name == "string":
            return "str"
        if ty.name == "bool":
            return "bool"
        if ty.name in ("u32", "u64", "s32", "s64"):
            return "int"
        if ty.name in ("f32", "f64"):
            return "float"
        return ty.name
    if isinstance(ty, WitList):
        inner = _py_type_annotation(ty.element, type_map)
        return f"list[{inner}]"
    if isinstance(ty, WitOption):
        inner = _py_type_annotation(ty.inner, type_map)
        return f"{inner} | None"
    if isinstance(ty, WitResult):
        ok_ann = _py_type_annotation(ty.ok, type_map) if ty.ok else "None"
        err_ann = _py_type_annotation(ty.err, type_map) if ty.err else "None"
        return f"Result[{ok_ann}, {err_ann}]"
    if isinstance(ty, WitRef):
        defn = type_map.get(ty.name)
        if isinstance(defn, WitEnum):
            return "str"
        if isinstance(defn, WitVariant):
            return kebab_to_pascal(ty.name)
        if isinstance(defn, WitRecord):
            return kebab_to_pascal(ty.name)
        return kebab_to_pascal(ty.name)
    return "Any"


# ---------------------------------------------------------------------------
# _types.py generation
# ---------------------------------------------------------------------------


def generate_types(world: WitWorld) -> str:
    """Generate _types.py content."""
    type_map = _build_type_map(world)
    lines: list[str] = [GENERATED_HEADER]
    lines.append("from __future__ import annotations\n")
    lines.append("from dataclasses import dataclass")
    lines.append("from typing import Generic, TypeVar, Union\n")
    lines.append('T = TypeVar("T")')
    lines.append('E = TypeVar("E")\n')

    # Result wrappers (always emitted)
    lines.append("")
    lines.append("")
    lines.append("@dataclass(frozen=True, slots=True)")
    lines.append("class Ok(Generic[T]):")
    lines.append('    """Wraps the success value from a WIT ``result<T, E>``."""\n')
    lines.append("    value: T\n")
    lines.append("")
    lines.append("@dataclass(frozen=True, slots=True)")
    lines.append("class Err(Generic[E]):")
    lines.append('    """Wraps the error value from a WIT ``result<T, E>``."""\n')
    lines.append("    value: E\n")
    lines.append("")
    lines.append("Result = Union[Ok[T], Err[E]]")

    # Collect all types to emit (world types + imported variant/record types)
    all_types = list(world.types)
    for imp in world.imports:
        for t in imp.types:
            # Only emit non-enum, non-alias types from imports
            if isinstance(t, (WitRecord, WitVariant)):
                all_types.append(t)

    for typedef in all_types:
        lines.append("")
        lines.append("")
        if isinstance(typedef, WitRecord):
            lines.extend(_gen_record(typedef, type_map))
        elif isinstance(typedef, WitVariant):
            lines.extend(_gen_variant(typedef, type_map))
        elif isinstance(typedef, WitEnum):
            lines.extend(_gen_enum(typedef))
        elif isinstance(typedef, WitTypeAlias):
            pass  # Expand inline, no Python type emitted

    lines.append("")
    return "\n".join(lines)


def _gen_record(record: WitRecord, type_map: dict[str, WitTypeDef]) -> list[str]:
    lines: list[str] = []
    cls_name = kebab_to_pascal(record.name)
    lines.append("@dataclass(frozen=True, slots=True)")
    lines.append(f"class {cls_name}:")
    lines.append(f'    """WIT ``{record.name}`` record."""\n')
    for field in record.fields:
        py_name = kebab_to_snake(field.name)
        py_type = _py_type_annotation(field.type, type_map)
        lines.append(f"    {py_name}: {py_type}")
    if not record.fields:
        lines.append("    pass")
    return lines


def _gen_variant(variant: WitVariant, type_map: dict[str, WitTypeDef]) -> list[str]:
    lines: list[str] = []

    # Check if this is a "record-reference" variant (all cases point to named records)
    if _variant_has_overlapping_record_cases(variant, type_map):
        # Emit as Union of the referenced record types
        case_types = []
        for case in variant.cases:
            assert isinstance(case.payload, WitRef)
            case_types.append(kebab_to_pascal(case.payload.name))
        union_name = kebab_to_pascal(variant.name)
        members = ", ".join(case_types)
        lines.append(f"{union_name} = Union[{members}]")
        return lines

    # Mixed variant: some unit cases, some payload cases
    case_classes: list[str] = []
    for case in variant.cases:
        cls_name = variant_case_class_name(variant.name, case.name)
        case_classes.append(cls_name)
        if _is_unit_variant_case(case):
            lines.append("@dataclass(frozen=True, slots=True)")
            lines.append(f"class {cls_name}:")
            lines.append(
                f'    """WIT ``{variant.name}::{case.name}`` (unit variant case)."""'
            )
            lines.append("")
            lines.append("")
        else:
            assert case.payload is not None
            # Determine field name from config override or default
            field_name = _variant_payload_field_name(
                variant.name, case.name, case.payload, type_map
            )
            py_type = _py_type_annotation(case.payload, type_map)
            lines.append("@dataclass(frozen=True, slots=True)")
            lines.append(f"class {cls_name}:")
            lines.append(f'    """WIT ``{variant.name}::{case.name}`` variant case."""')
            lines.append("")
            lines.append(f"    {field_name}: {py_type}")
            lines.append("")
            lines.append("")

    # Emit Union type alias
    union_name = kebab_to_pascal(variant.name)
    if len(case_classes) == 1:
        lines.append(f"{union_name} = {case_classes[0]}")
    else:
        members = ",\n    ".join(case_classes)
        lines.append(f"{union_name} = Union[")
        lines.append(f"    {members},")
        lines.append("]")
    return lines


def _variant_payload_field_name(
    variant_name: str,
    case_name: str,
    payload: WitType,
    type_map: dict[str, WitTypeDef],
) -> str:
    """Determine the field name for a variant case payload.

    Uses config overrides or defaults to 'value'. For list payloads
    of entity types, returns 'entities' based on the field_overrides config.
    """
    key = f"{variant_name}.{case_name}"
    if key in _field_overrides:
        return _field_overrides[key]
    return "value"


# Module-level field overrides, set once before generation via init_field_overrides().
_field_overrides: dict[str, str] = {}


def init_field_overrides(overrides: dict[str, str]) -> None:
    """Set variant case field name overrides from config. Call once before generating."""
    _field_overrides.clear()
    _field_overrides.update(overrides)


def _gen_enum(enum: WitEnum) -> list[str]:
    lines: list[str] = []
    lines.append(f"# WIT enum ``{enum.name}``: {', '.join(enum.cases)}")
    lines.append(f"# Represented as plain str at runtime (no Python class needed).")
    return lines


# ---------------------------------------------------------------------------
# _convert.py generation
# ---------------------------------------------------------------------------


def generate_convert(world: WitWorld) -> str:
    """Generate _convert.py content."""
    type_map = _build_type_map(world)
    lines: list[str] = [GENERATED_HEADER]
    lines.append("from __future__ import annotations\n")
    lines.append("from typing import Any\n")

    # FIXME comment and imports
    lines.append(
        "# FIXME(wasmtime-py): v40 does not export Record/Variant from a public path;"
    )
    lines.append(
        "# wasmtime.component._types is the only way to access them.  Revisit when"
    )
    lines.append("# wasmtime-py exposes a public API for component-model types.")
    lines.append("from wasmtime.component._types import Record, Variant\n")

    # Import types from _types
    type_imports = _collect_type_imports(world, type_map)
    if type_imports:
        lines.append("from ._types import (")
        for name in sorted(type_imports, key=str.casefold):
            lines.append(f"    {name},")
        lines.append(")\n")

    # _rec helper
    lines.append("")
    lines.append("def _rec(**kwargs: Any) -> Record:")
    lines.append('    """Build a wasmtime Record with kebab-case attributes."""')
    lines.append("    r = Record()")
    lines.append("    r.__dict__.update(kwargs)")
    lines.append("    return r")

    # Discover all types needing to_wasm/from_wasm converters
    to_wasm_needed: list[str] = []  # type names in dependency order
    from_wasm_needed: list[str] = []

    def _discover_to_wasm(ty: WitType, seen: set[str]) -> None:
        """Recursively find all types needing to_wasm converters."""
        if isinstance(ty, WitRef):
            if ty.name in seen:
                return
            defn = type_map.get(ty.name)
            if isinstance(defn, WitVariant):
                # First discover sub-types
                for case in defn.cases:
                    if case.payload is not None:
                        _discover_to_wasm(case.payload, seen)
                if ty.name not in seen:
                    seen.add(ty.name)
                    to_wasm_needed.append(ty.name)
            elif isinstance(defn, WitRecord):
                if _record_has_variant_fields(defn, type_map):
                    for f in defn.fields:
                        _discover_to_wasm(f.type, seen)
                    if ty.name not in seen:
                        seen.add(ty.name)
                        to_wasm_needed.append(ty.name)
        elif isinstance(ty, WitList):
            _discover_to_wasm(ty.element, seen)

    def _discover_from_wasm(ty: WitType, seen: set[str]) -> None:
        """Recursively find all types needing from_wasm converters."""
        if isinstance(ty, WitRef):
            if ty.name in seen:
                return
            defn = type_map.get(ty.name)
            if isinstance(defn, WitVariant):
                if not _variant_has_overlapping_record_cases(defn, type_map):
                    seen.add(ty.name)
                    from_wasm_needed.append(ty.name)
            elif isinstance(defn, WitRecord):
                if _record_needs_from_wasm(defn, type_map):
                    # First discover field types
                    for f in defn.fields:
                        _discover_from_wasm(f.type, seen)
                    if ty.name not in seen:
                        seen.add(ty.name)
                        from_wasm_needed.append(ty.name)
        elif isinstance(ty, WitList):
            _discover_from_wasm(ty.element, seen)
        elif isinstance(ty, WitResult):
            if ty.ok:
                _discover_from_wasm(ty.ok, seen)

    to_seen: set[str] = set()
    from_seen: set[str] = set()
    for export in world.exports:
        for param in export.params:
            _discover_to_wasm(param.type, to_seen)
        if export.result is not None:
            _discover_from_wasm(export.result, from_seen)

    # Generate to_wasm functions (dependency order)
    emitted: set[str] = set()
    for type_name in to_wasm_needed:
        defn = type_map[type_name]
        func_name = f"to_wasm_{kebab_to_snake(type_name)}"
        if func_name not in emitted:
            emitted.add(func_name)
            lines.append("")
            lines.append("")
            if isinstance(defn, WitVariant):
                lines.extend(_gen_to_wasm_variant(defn, type_map))
            elif isinstance(defn, WitRecord):
                lines.extend(_gen_to_wasm_record(defn, type_map))

    # Generate from_wasm functions for nested types (dependency order)
    for type_name in from_wasm_needed:
        defn = type_map[type_name]
        func_name = f"from_wasm_{kebab_to_snake(type_name)}"
        if func_name not in emitted:
            emitted.add(func_name)
            lines.append("")
            lines.append("")
            if isinstance(defn, WitVariant):
                lines.extend(_gen_from_wasm_variant(defn, type_map))
            elif isinstance(defn, WitRecord):
                lines.extend(_gen_from_wasm_standalone_record(defn, type_map))

    # Generate from_wasm functions for export results
    for export in world.exports:
        if export.result is not None:
            lines.append("")
            lines.append("")
            lines.extend(_gen_from_wasm_export(export, type_map))

    lines.append("")
    return "\n".join(lines)


def _collect_type_imports(world: WitWorld, type_map: dict[str, WitTypeDef]) -> set[str]:
    """Collect all Python type names needed in _convert.py."""
    names: set[str] = {"Ok", "Err", "Result"}
    for typedef in world.types:
        if isinstance(typedef, WitRecord):
            names.add(kebab_to_pascal(typedef.name))
        elif isinstance(typedef, WitVariant):
            if _variant_has_overlapping_record_cases(typedef, type_map):
                names.add(kebab_to_pascal(typedef.name))
                for case in typedef.cases:
                    assert isinstance(case.payload, WitRef)
                    names.add(kebab_to_pascal(case.payload.name))
            else:
                names.add(kebab_to_pascal(typedef.name))
                for case in typedef.cases:
                    cls = variant_case_class_name(typedef.name, case.name)
                    names.add(cls)
    for imp in world.imports:
        for typedef in imp.types:
            if isinstance(typedef, WitVariant):
                names.add(kebab_to_pascal(typedef.name))
                for case in typedef.cases:
                    cls = variant_case_class_name(typedef.name, case.name)
                    names.add(cls)
    return names


def _record_has_variant_fields(
    record: WitRecord, type_map: dict[str, WitTypeDef]
) -> bool:
    for field in record.fields:
        resolved = _resolve_type(field.type, type_map)
        if isinstance(resolved, WitRef):
            defn = type_map.get(resolved.name)
            if isinstance(defn, WitVariant):
                return True
    return False


def _gen_to_wasm_variant(
    variant: WitVariant, type_map: dict[str, WitTypeDef]
) -> list[str]:
    """Generate to_wasm function for a variant type."""
    func_name = f"to_wasm_{kebab_to_snake(variant.name)}"
    py_type = kebab_to_pascal(variant.name)
    lines: list[str] = []

    # Check if this is a record-reference variant
    if _variant_has_overlapping_record_cases(variant, type_map):
        lines.append(f"def {func_name}(config: {py_type}) -> Variant:")
        lines.append(f'    """Convert {py_type} union to a wasmtime Variant."""')
        for i, case in enumerate(variant.cases):
            assert isinstance(case.payload, WitRef)
            record_def = type_map.get(case.payload.name)
            assert isinstance(record_def, WitRecord)
            cls = kebab_to_pascal(case.payload.name)
            prefix = "if" if i == 0 else "elif" if i < len(variant.cases) - 1 else None
            if prefix is not None:
                lines.append(f"    {prefix} isinstance(config, {cls}):")
                lines.append(f"        return Variant(")
                lines.append(f'            "{case.name}",')
                lines.append(f"            {_gen_record_to_rec(record_def, 'config')},")
                lines.append(f"        )")
            else:
                # last case: no isinstance check
                lines.append(f"    return Variant(")
                lines.append(f'        "{case.name}",')
                lines.append(f"        {_gen_record_to_rec(record_def, 'config')},")
                lines.append(f"    )")
        return lines

    # Mixed variant (unit + payload cases)
    lines.append(f"def {func_name}(entity: {py_type}) -> Variant:")
    lines.append(f'    """Convert a {py_type} to a wasmtime Variant."""')
    for case in variant.cases:
        cls = variant_case_class_name(variant.name, case.name)
        if _is_unit_variant_case(case):
            lines.append(f"    if isinstance(entity, {cls}):")
            lines.append(f'        return Variant("{case.name}")')
        else:
            assert case.payload is not None
            field_name = _variant_payload_field_name(
                variant.name, case.name, case.payload, type_map
            )
            # Check if the payload needs conversion
            value_expr = f"entity.{field_name}"
            value_expr = _gen_field_to_wasm(value_expr, case.payload, type_map)
            lines.append(f"    if isinstance(entity, {cls}):")
            lines.append(f'        return Variant("{case.name}", {value_expr})')
    # Fallback (should be unreachable)
    lines.append(f'    raise TypeError(f"Unknown {py_type}: {{type(entity)}}")')
    return lines


def _gen_field_to_wasm(
    expr: str,
    ty: WitType,
    type_map: dict[str, WitTypeDef],
) -> str:
    """Generate expression to convert a field to wasmtime format."""
    if isinstance(ty, WitRef):
        defn = type_map.get(ty.name)
        if isinstance(defn, WitVariant):
            converter = f"to_wasm_{kebab_to_snake(ty.name)}"
            return f"{converter}({expr})"
    elif isinstance(ty, WitList):
        if isinstance(ty.element, WitRef):
            defn = type_map.get(ty.element.name)
            if isinstance(defn, WitVariant):
                converter = f"to_wasm_{kebab_to_snake(ty.element.name)}"
                return f"[{converter}(e) for e in {expr}]"
    return expr


def _gen_from_wasm_variant(
    variant: WitVariant, type_map: dict[str, WitTypeDef]
) -> list[str]:
    """Generate from_wasm function for a variant with mixed cases."""
    func_name = f"from_wasm_{kebab_to_snake(variant.name)}"
    py_type = kebab_to_pascal(variant.name)
    lines: list[str] = []
    lines.append(f"def {func_name}(raw: Any) -> {py_type}:")
    lines.append(f'    """Convert a wasmtime Variant to {py_type}."""')
    lines.append("    if not isinstance(raw, Variant):")
    lines.append(
        f'        raise TypeError(f"expected Variant for {variant.name}, got {{type(raw)}}")'
    )
    lines.append("    tag = raw.tag")
    for case in variant.cases:
        cls = variant_case_class_name(variant.name, case.name)
        if _is_unit_variant_case(case):
            lines.append(f'    if tag == "{case.name}":')
            lines.append(f"        return {cls}()")
        else:
            assert case.payload is not None
            resolved_payload = _resolve_type(case.payload, type_map)
            if (
                isinstance(resolved_payload, WitPrimitive)
                and resolved_payload.name == "string"
            ):
                payload_expr = "str(raw.payload)"
            else:
                payload_expr = "raw.payload"
            lines.append(f'    if tag == "{case.name}":')
            lines.append(f"        return {cls}({payload_expr})")
    lines.append(f'    raise ValueError(f"Unknown {variant.name} tag: {{tag}}")')
    return lines


def _gen_from_wasm_standalone_record(
    record: WitRecord, type_map: dict[str, WitTypeDef]
) -> list[str]:
    """Generate from_wasm function for a standalone record."""
    func_name = f"from_wasm_{kebab_to_snake(record.name)}"
    cls = kebab_to_pascal(record.name)
    lines: list[str] = []
    lines.append(f"def {func_name}(raw: Any) -> {cls}:")
    lines.append(f'    """Convert a wasmtime Record to {cls}."""')
    lines.append(f"    return {cls}(")
    for field in record.fields:
        py_name = kebab_to_snake(field.name)
        kebab_name = field.name
        if "-" in kebab_name:
            accessor = f'getattr(raw, "{kebab_name}")'
        else:
            accessor = f"raw.{kebab_name}"
        value_expr = _gen_field_from_wasm(accessor, field.type, type_map)
        lines.append(f"        {py_name}={value_expr},")
    lines.append(f"    )")
    return lines


def _gen_record_to_rec(record: WitRecord, var: str) -> str:
    """Generate a _rec(...) call to convert a Python record to wasmtime Record."""
    parts: list[str] = []
    for field in record.fields:
        py_name = kebab_to_snake(field.name)
        kebab_name = field.name
        if "-" in kebab_name:
            parts.append(f'**{{"{kebab_name}": {var}.{py_name}}}')
        else:
            parts.append(f"{kebab_name}={var}.{py_name}")
    args = ", ".join(parts)
    return f"_rec({args})"


def _gen_to_wasm_record(
    record: WitRecord, type_map: dict[str, WitTypeDef]
) -> list[str]:
    """Generate to_wasm function for a record with variant fields."""
    func_name = f"to_wasm_{kebab_to_snake(record.name)}"
    py_type = kebab_to_pascal(record.name)
    lines: list[str] = []
    lines.append(f"def {func_name}(config: {py_type}) -> Record:")
    lines.append(f'    """Convert {py_type} to a wasmtime Record."""')
    lines.append(f"    return _rec(")
    for field in record.fields:
        py_name = kebab_to_snake(field.name)
        kebab_name = field.name
        resolved = _resolve_type(field.type, type_map)
        # Check if this field needs conversion
        value_expr = f"config.{py_name}"
        if isinstance(resolved, WitRef):
            defn = type_map.get(resolved.name)
            if isinstance(defn, WitVariant):
                converter = f"to_wasm_{kebab_to_snake(resolved.name)}"
                value_expr = f"{converter}({value_expr})"
        if "-" in kebab_name:
            lines.append(f'        **{{"{kebab_name}": {value_expr}}},')
        else:
            lines.append(f"        {kebab_name}={value_expr},")
    lines.append(f"    )")
    return lines


def _gen_from_wasm_export(
    export: WitFunc, type_map: dict[str, WitTypeDef]
) -> list[str]:
    """Generate from_wasm function for an export's result type."""
    func_name = f"from_wasm_{kebab_to_snake(export.name)}"
    result_type = export.result
    assert result_type is not None

    lines: list[str] = []

    if isinstance(result_type, WitResult):
        return _gen_from_wasm_result(func_name, export.name, result_type, type_map)
    elif isinstance(result_type, WitRef):
        # Direct record return (no result wrapper)
        defn = type_map.get(result_type.name)
        if isinstance(defn, WitRecord):
            return _gen_from_wasm_direct_record(func_name, export.name, defn, type_map)

    return lines


def _gen_from_wasm_result(
    func_name: str,
    export_name: str,
    result: WitResult,
    type_map: dict[str, WitTypeDef],
) -> list[str]:
    lines: list[str] = []
    ok_type = result.ok
    err_type = result.err

    # Determine dispatch strategy
    ok_is_record = False
    ok_is_string = False
    ok_is_none = ok_type is None
    err_is_string = isinstance(err_type, WitPrimitive) and err_type.name == "string"

    if ok_type is not None:
        resolved_ok = _resolve_type(ok_type, type_map)
        if isinstance(resolved_ok, WitRef):
            defn = type_map.get(resolved_ok.name)
            ok_is_record = isinstance(defn, WitRecord)
        elif isinstance(resolved_ok, WitPrimitive) and resolved_ok.name == "string":
            ok_is_string = True

    # Determine Python return type annotation
    if ok_is_none:
        ret_ann = "Result[None, str]"
    elif ok_is_string:
        ret_ann = "Result[str, str]"
    elif ok_is_record and isinstance(ok_type, WitRef):
        ret_ann = f"Result[{kebab_to_pascal(ok_type.name)}, str]"
    else:
        ret_ann = "Any"

    lines.append(f"def {func_name}(raw: Any) -> {ret_ann}:")
    lines.append(f'    """Convert {export_name} result."""')

    if ok_is_none and err_is_string:
        # result<_, string> → untagged: None=Ok, str=Err
        lines.append("    if raw is None:")
        lines.append("        return Ok(None)")
        lines.append("    if not isinstance(raw, str):")
        lines.append(
            f'        raise TypeError(f"expected str error from {export_name}, got {{type(raw)}}")'
        )
        lines.append("    return Err(raw)")
    elif ok_is_string and err_is_string:
        # result<string, string> → tagged: Variant("ok"/"err", str)
        lines.append("    if not isinstance(raw, Variant):")
        lines.append(
            f'        raise TypeError(f"expected Variant from {export_name}, got {{type(raw)}}")'
        )
        lines.append("    if not isinstance(raw.payload, str):")
        lines.append(
            f'        raise TypeError(f"expected str payload in {export_name} result, got {{type(raw.payload)}}")'
        )
        lines.append('    if raw.tag == "ok":')
        lines.append("        return Ok(raw.payload)")
        lines.append('    if raw.tag == "err":')
        lines.append("        return Err(raw.payload)")
        lines.append(
            f'    raise ValueError(f"Unknown {export_name} result tag: {{raw.tag}}")'
        )
    elif ok_is_record and err_is_string:
        # result<record, string> → untagged: Record=Ok, str=Err
        assert isinstance(ok_type, WitRef)
        record_def = type_map.get(ok_type.name)
        assert isinstance(record_def, WitRecord)
        lines.append("    if isinstance(raw, str):")
        lines.append("        return Err(raw)")
        # Delegate to standalone converter if one exists for this record
        if _record_needs_from_wasm(record_def, type_map):
            converter = f"from_wasm_{kebab_to_snake(ok_type.name)}"
            lines.append(f"    return Ok({converter}(raw))")
        else:
            lines.append("    return Ok(")
            lines.extend(_gen_record_from_raw(record_def, type_map, indent=8))
            lines.append("    )")
    else:
        lines.append("    return raw  # TODO: unhandled result type")

    return lines


def _gen_record_from_raw(
    record: WitRecord,
    type_map: dict[str, WitTypeDef],
    indent: int = 8,
) -> list[str]:
    """Generate record construction from raw wasmtime value."""
    pad = " " * indent
    cls = kebab_to_pascal(record.name)
    lines: list[str] = []
    lines.append(f"{pad}{cls}(")
    for field in record.fields:
        py_name = kebab_to_snake(field.name)
        kebab_name = field.name
        # Access via getattr for multi-word, direct for single-word
        if "-" in kebab_name:
            accessor = f'getattr(raw, "{kebab_name}")'
        else:
            accessor = f"raw.{kebab_name}"

        value_expr = _gen_field_from_wasm(accessor, field.type, type_map)
        lines.append(f"{pad}    {py_name}={value_expr},")
    lines.append(f"{pad})")
    return lines


def _gen_field_from_wasm(
    accessor: str,
    ty: WitType,
    type_map: dict[str, WitTypeDef],
) -> str:
    """Generate expression to convert a field value from wasmtime."""
    if isinstance(ty, WitRef):
        defn = type_map.get(ty.name)
        if isinstance(defn, WitRecord):
            if _record_needs_from_wasm(defn, type_map):
                converter = f"from_wasm_{kebab_to_snake(ty.name)}"
                return f"{converter}({accessor})"
        elif isinstance(defn, WitVariant):
            converter = f"from_wasm_{kebab_to_snake(ty.name)}"
            return f"{converter}({accessor})"
    elif isinstance(ty, WitList):
        if isinstance(ty.element, WitRef):
            defn = type_map.get(ty.element.name)
            if isinstance(defn, WitRecord) and _record_needs_from_wasm(defn, type_map):
                converter = f"from_wasm_{kebab_to_snake(ty.element.name)}"
                return f"[{converter}(e) for e in {accessor}]"
    return accessor


def _record_needs_from_wasm(record: WitRecord, type_map: dict[str, WitTypeDef]) -> bool:
    """Check if a record needs a from_wasm converter (has multi-word fields or variant fields)."""
    for field in record.fields:
        if "-" in field.name:
            return True
        if isinstance(field.type, WitRef):
            defn = type_map.get(field.type.name)
            if isinstance(defn, WitVariant):
                return True
            if isinstance(defn, WitRecord) and _record_needs_from_wasm(defn, type_map):
                return True
        elif isinstance(field.type, WitList):
            if isinstance(field.type.element, WitRef):
                inner_defn = type_map.get(field.type.element.name)
                if isinstance(inner_defn, WitRecord) and _record_needs_from_wasm(
                    inner_defn, type_map
                ):
                    return True
    return False


def _gen_from_wasm_direct_record(
    func_name: str,
    export_name: str,
    record: WitRecord,
    type_map: dict[str, WitTypeDef],
) -> list[str]:
    """Generate from_wasm for a direct record return (no result wrapper)."""
    cls = kebab_to_pascal(record.name)
    standalone = f"from_wasm_{kebab_to_snake(record.name)}"
    lines: list[str] = []
    lines.append(f"def {func_name}(raw: Any) -> {cls}:")
    lines.append(f'    """Convert {export_name} result (direct Record)."""')
    # Delegate to standalone converter if one exists and has a different name
    if _record_needs_from_wasm(record, type_map) and standalone != func_name:
        lines.append(f"    return {standalone}(raw)")
    else:
        lines.append(f"    return {cls}(")
        for field in record.fields:
            py_name = kebab_to_snake(field.name)
            kebab_name = field.name
            if "-" in kebab_name:
                accessor = f'getattr(raw, "{kebab_name}")'
            else:
                accessor = f"raw.{kebab_name}"
            value_expr = _gen_field_from_wasm(accessor, field.type, type_map)
            lines.append(f"        {py_name}={value_expr},")
        lines.append(f"    )")
    return lines


# ---------------------------------------------------------------------------
# _component.py generation
# ---------------------------------------------------------------------------


def generate_component(world: WitWorld) -> str:
    """Generate _component.py content."""
    type_map = _build_type_map(world)
    lines: list[str] = [GENERATED_HEADER]
    lines.append("from __future__ import annotations\n")
    lines.append("import threading\n")
    lines.append("from typing import Any\n")
    lines.append("from wasmtime import Engine, Store")
    lines.append("from wasmtime import component as cm\n")

    # Collect imports needed
    convert_imports = _collect_convert_imports(world, type_map)
    type_imports_for_component = _collect_component_type_imports(world, type_map)

    lines.append("from ._convert import (")
    for name in sorted(convert_imports, key=str.casefold):
        lines.append(f"    {name},")
    lines.append(")")

    lines.append("from ._imports import ImportCallbacks, wire_imports")

    lines.append("from ._types import (")
    for name in sorted(type_imports_for_component, key=str.casefold):
        lines.append(f"    {name},")
    lines.append(")\n")

    # Class definition
    lines.append("")
    lines.append("class AnalyzeComponent:")
    lines.append(
        '    """Reusable wrapper around the full arcjet-analyze WASM component."""\n'
    )

    # __init__
    lines.append("    def __init__(")
    lines.append("        self,")
    lines.append("        wasm_path: str,")
    lines.append("        callbacks: ImportCallbacks | None = None,")
    lines.append("    ) -> None:")
    lines.append("        self._engine = Engine()")
    lines.append(
        "        self._component = cm.Component.from_file(self._engine, wasm_path)"
    )
    lines.append("        self._linker = cm.Linker(self._engine)")
    lines.append("        self._linker.allow_shadowing = True")
    lines.append("")
    lines.append("        wire_imports(self._linker, self._component, callbacks)")
    lines.append("")
    lines.append(
        "        # Lock for thread safety: wasmtime-py wrappers have unprotected"
    )
    lines.append(
        "        # mutable state (Slab globals, attribute reads). A per-instance"
    )
    lines.append(
        "        # lock around _call() provides defensive safety at negligible"
    )
    lines.append("        # cost (WASM calls are 1-5ms).")
    lines.append("        self._call_lock = threading.Lock()")

    # _call
    lines.append("")
    lines.append("    def _call(self, export_name: str, *args: Any) -> Any:")
    lines.append('        """Call a named export with a fresh Store."""')
    lines.append("        with self._call_lock:")
    lines.append("            store = Store(self._engine)")
    lines.append(
        "            instance = self._linker.instantiate(store, self._component)"
    )
    lines.append("            func = instance.get_func(store, export_name)")
    lines.append("            if func is None:")
    lines.append(
        '                raise RuntimeError(f"{export_name} export not found in component")'
    )
    lines.append("            return func(store, *args)")

    # Export methods
    for export in world.exports:
        lines.append("")
        lines.extend(_gen_export_method(export, type_map))

    lines.append("")
    return "\n".join(lines)


def _gen_export_method(export: WitFunc, type_map: dict[str, WitTypeDef]) -> list[str]:
    """Generate a method for a single export."""
    method_name = kebab_to_snake(export.name)
    lines: list[str] = []

    # Build parameter list
    params: list[str] = ["self"]
    for p in export.params:
        py_name = kebab_to_snake(p.name)
        py_type = _py_type_annotation(p.type, type_map)
        params.append(f"{py_name}: {py_type}")

    # Return type
    if export.result is not None:
        ret_type = _py_type_annotation(export.result, type_map)
    else:
        ret_type = "None"

    # Method signature
    param_str = ",\n        ".join(params)
    lines.append(f"    def {method_name}(")
    lines.append(f"        {param_str},")
    lines.append(f"    ) -> {ret_type}:")
    lines.append(f'        """Run ``{export.name}`` on the component."""')

    # Build call arguments
    call_args: list[str] = []
    for p in export.params:
        py_name = kebab_to_snake(p.name)
        if isinstance(p.type, WitRef):
            defn = type_map.get(p.type.name)
            if isinstance(defn, WitVariant):
                converter = f"to_wasm_{kebab_to_snake(p.type.name)}"
                call_args.append(f"{converter}({py_name})")
                continue
            elif isinstance(defn, WitRecord) and _record_has_variant_fields(
                defn, type_map
            ):
                converter = f"to_wasm_{kebab_to_snake(p.type.name)}"
                call_args.append(f"{converter}({py_name})")
                continue
        call_args.append(py_name)

    args_str = ", ".join(call_args)

    # Generate call + conversion
    converter_name = f"from_wasm_{method_name}"
    lines.append(f'        raw = self._call("{export.name}", {args_str})')
    lines.append(f"        return {converter_name}(raw)")

    return lines


def _collect_convert_imports(
    world: WitWorld, type_map: dict[str, WitTypeDef]
) -> set[str]:
    """Collect from_wasm/to_wasm function names needed in _component.py."""
    names: set[str] = set()
    for export in world.exports:
        method_name = kebab_to_snake(export.name)
        names.add(f"from_wasm_{method_name}")
        for p in export.params:
            if isinstance(p.type, WitRef):
                defn = type_map.get(p.type.name)
                if isinstance(defn, WitVariant):
                    names.add(f"to_wasm_{kebab_to_snake(p.type.name)}")
                elif isinstance(defn, WitRecord) and _record_has_variant_fields(
                    defn, type_map
                ):
                    names.add(f"to_wasm_{kebab_to_snake(p.type.name)}")
    return names


def _collect_component_type_imports(
    world: WitWorld, type_map: dict[str, WitTypeDef]
) -> set[str]:
    """Collect type names needed in _component.py."""
    names: set[str] = set()
    for export in world.exports:
        # Return type
        if export.result is not None:
            _collect_type_refs(export.result, type_map, names)
        # Param types
        for p in export.params:
            _collect_type_refs(p.type, type_map, names)
    return names


def _collect_type_refs(
    ty: WitType,
    type_map: dict[str, WitTypeDef],
    names: set[str],
) -> None:
    """Recursively collect Python type names referenced by a WIT type."""
    if isinstance(ty, WitRef):
        defn = type_map.get(ty.name)
        if isinstance(defn, WitEnum):
            return  # enums are str
        if isinstance(defn, WitTypeAlias):
            _collect_type_refs(defn.target, type_map, names)
            return
        if isinstance(defn, WitVariant):
            if _variant_has_overlapping_record_cases(defn, type_map):
                names.add(kebab_to_pascal(ty.name))
                for case in defn.cases:
                    assert isinstance(case.payload, WitRef)
                    names.add(kebab_to_pascal(case.payload.name))
            else:
                names.add(kebab_to_pascal(ty.name))
        elif isinstance(defn, WitRecord):
            names.add(kebab_to_pascal(ty.name))
    elif isinstance(ty, WitResult):
        names.add("Result")
        if ty.ok:
            _collect_type_refs(ty.ok, type_map, names)
        if ty.err:
            _collect_type_refs(ty.err, type_map, names)
    elif isinstance(ty, WitList):
        _collect_type_refs(ty.element, type_map, names)
    elif isinstance(ty, WitOption):
        _collect_type_refs(ty.inner, type_map, names)


# ---------------------------------------------------------------------------
# _imports.py generation
# ---------------------------------------------------------------------------


def generate_imports(world: WitWorld) -> str:
    """Generate _imports.py content."""
    type_map = _build_type_map(world)
    lines: list[str] = [GENERATED_HEADER]
    lines.append("from __future__ import annotations\n")
    lines.append("from dataclasses import dataclass")
    lines.append("from typing import Callable\n")
    lines.append("from wasmtime import Store")
    lines.append("from wasmtime import component as cm\n")

    # FIXME comment and imports
    lines.append("# FIXME(wasmtime-py): v40 does not export these from a public path;")
    lines.append(
        "# wasmtime.component._types is the only way to access them.  Revisit when"
    )
    lines.append("# wasmtime-py exposes a public API for component-model types.")
    lines.append("from wasmtime.component._types import (")
    lines.append("    OptionType,")
    lines.append("    ResultType,")
    lines.append("    Variant,")
    lines.append("    VariantLikeType,")
    lines.append("    VariantType,")
    lines.append(")\n")

    # Import from _convert and _types
    lines.append("from ._convert import to_wasm_sensitive_info_entity")
    lines.append("from ._types import SensitiveInfoEntity\n")

    # MRO fix
    lines.append(
        "# FIXME(wasmtime-py): v40 MRO bug workaround — remove when fixed upstream."
    )
    lines.append("try:")
    lines.append("    _real_add_classes = VariantLikeType.add_classes")
    lines.append("    for _cls in (VariantType, OptionType, ResultType):")
    lines.append("        if _cls.add_classes is not _real_add_classes:")
    lines.append(
        "            _cls.add_classes = _real_add_classes  # type: ignore[assignment]"
    )
    lines.append("except (AttributeError, TypeError):")
    lines.append(
        "    pass  # Future wasmtime-py may fix this or restructure these classes"
    )

    # ImportCallbacks dataclass
    lines.append("")
    lines.append("")
    lines.append("@dataclass(frozen=True, slots=True)")
    lines.append("class ImportCallbacks:")
    lines.append('    """User-provided callbacks for component import interfaces."""\n')
    # Generate one field per import function
    for imp in world.imports:
        for func in imp.funcs:
            field_name = _import_callback_field_name(imp.name, func)
            cb_type = _import_callback_type(func, type_map, imp)
            lines.append(f"    {field_name}: {cb_type} | None = None")

    # wire_imports
    lines.append("")
    lines.append("")
    lines.append("def wire_imports(")
    lines.append("    linker: cm.Linker,")
    lines.append("    component: cm.Component,")
    lines.append("    callbacks: ImportCallbacks | None = None,")
    lines.append(") -> None:")
    lines.append(
        '    """Wire all import interfaces into *linker* using trap-then-shadow."""'
    )
    lines.append("    cb = callbacks or ImportCallbacks()")
    lines.append("")
    lines.append("    # 1. Trap everything first")
    lines.append("    linker.define_unknown_imports_as_traps(component)")
    lines.append("")

    # Import default implementations
    default_names: list[str] = []
    for imp in world.imports:
        for func in imp.funcs:
            default_names.append(_import_default_func_name(imp.name, func))
    lines.append("    from ._import_defaults import (")
    for name in sorted(default_names, key=str.casefold):
        lines.append(f"        {name},")
    lines.append("    )\n")

    # Resolve callbacks with defaults
    for imp in world.imports:
        for func in imp.funcs:
            field_name = _import_callback_field_name(imp.name, func)
            default_name = _import_default_func_name(imp.name, func)
            local_name = f"{field_name}_fn"
            lines.append(f"    {local_name} = cb.{field_name} or {default_name}")
    lines.append("")

    # Wire imports
    lines.append("    # 2. Override with real implementations")
    lines.append("    with linker.root() as root:")
    for imp in world.imports:
        iface_name = imp.name
        lines.append(f'        with root.add_instance("{iface_name}") as iface:')
        for func in imp.funcs:
            field_name = _import_callback_field_name(imp.name, func)
            local_name = f"{field_name}_fn"
            wit_func_name = func.name

            # Check if this is the sensitive-info-detect special case
            is_si_detect = (
                "sensitive-information-identifier" in iface_name
                and func.name == "detect"
            )

            if is_si_detect:
                # Special handling: convert SensitiveInfoEntity → Variant
                lines.append("")
                lines.append(
                    f"            def _si_detect(_store: Store, tokens: list[str]) -> list[Variant | None]:"
                )
                lines.append(f"                results = {local_name}(tokens)")
                lines.append(f"                out: list[Variant | None] = []")
                lines.append(f"                for r in results:")
                lines.append(f"                    if r is None:")
                lines.append(f"                        out.append(None)")
                lines.append(f"                    else:")
                lines.append(
                    f"                        out.append(to_wasm_sensitive_info_entity(r))"
                )
                lines.append(f"                return out")
                lines.append("")
                lines.append(
                    f'            iface.add_func("{wit_func_name}", _si_detect)'
                )
            else:
                # Standard wiring
                param_count = len(func.params)
                if param_count == 1:
                    lines.append(
                        f"            iface.add_func("
                        f'"{wit_func_name}", '
                        f"lambda _store, a: {local_name}(a))"
                    )
                elif param_count == 2:
                    lines.append(
                        f"            iface.add_func("
                        f'"{wit_func_name}", '
                        f"lambda _store, a, b: {local_name}(a, b))"
                    )
                else:
                    lines.append(
                        f"            iface.add_func("
                        f'"{wit_func_name}", '
                        f"lambda _store, *args: {local_name}(*args))"
                    )

        lines.append("")

    lines.append("")
    return "\n".join(lines)


def _import_callback_field_name(iface_name: str, func: WitFunc) -> str:
    """Generate the ImportCallbacks field name for an import function."""
    short_iface = iface_name.split("/")[-1] if "/" in iface_name else iface_name
    # Special cases for well-known patterns
    if short_iface == "filter-overrides" and func.name == "ip-lookup":
        return "ip_lookup"
    if short_iface == "bot-identifier" and func.name == "detect":
        return "bot_detect"
    if short_iface == "verify-bot" and func.name == "verify":
        return "bot_verify"
    if short_iface == "sensitive-information-identifier" and func.name == "detect":
        return "sensitive_info_detect"
    # Default: use func name directly
    return kebab_to_snake(func.name)


def _import_default_func_name(iface_name: str, func: WitFunc) -> str:
    """Generate the default function name for an import function."""
    field = _import_callback_field_name(iface_name, func)
    return f"_default_{field}"


def _import_callback_type(
    func: WitFunc,
    type_map: dict[str, WitTypeDef],
    iface: WitInterface,
) -> str:
    """Generate the Callable type annotation for an import callback."""
    param_types: list[str] = []
    for p in func.params:
        param_types.append(_py_type_annotation(p.type, type_map))

    # Return type
    if func.result is not None:
        ret = _py_type_annotation(func.result, type_map)
    else:
        ret = "None"

    # Special case for sensitive-info detect
    iface_short = iface.name.split("/")[-1] if "/" in iface.name else iface.name
    if iface_short == "sensitive-information-identifier" and func.name == "detect":
        return "Callable[[list[str]], list[SensitiveInfoEntity | None]]"

    params = ", ".join(param_types)
    return f"Callable[[{params}], {ret}]"


# ---------------------------------------------------------------------------
# __init__.py generation
# ---------------------------------------------------------------------------


def generate_init(world: WitWorld) -> str:
    """Generate __init__.py content."""
    type_map = _build_type_map(world)
    lines: list[str] = [GENERATED_HEADER]
    lines.append("from ._component import AnalyzeComponent")
    lines.append("from ._imports import ImportCallbacks")

    # Collect all public type names
    all_names: list[str] = []
    all_names.extend(["Ok", "Err", "Result"])

    for typedef in world.types:
        if isinstance(typedef, WitRecord):
            all_names.append(kebab_to_pascal(typedef.name))
        elif isinstance(typedef, WitVariant):
            if _variant_has_overlapping_record_cases(typedef, type_map):
                all_names.append(kebab_to_pascal(typedef.name))
                for case in typedef.cases:
                    assert isinstance(case.payload, WitRef)
                    all_names.append(kebab_to_pascal(case.payload.name))
            else:
                all_names.append(kebab_to_pascal(typedef.name))
                for case in typedef.cases:
                    all_names.append(variant_case_class_name(typedef.name, case.name))
    # Import types (e.g., sensitive-info-entity variant)
    for imp in world.imports:
        for typedef in imp.types:
            if isinstance(typedef, WitVariant):
                all_names.append(kebab_to_pascal(typedef.name))
                for case in typedef.cases:
                    all_names.append(variant_case_class_name(typedef.name, case.name))

    # Generate import statement
    lines.append("from ._types import (")
    for name in sorted(set(all_names), key=str.casefold):
        lines.append(f"    {name},")
    lines.append(")\n")

    # __all__
    all_exports = ["AnalyzeComponent", "ImportCallbacks"] + sorted(set(all_names))
    lines.append("__all__ = [")
    for name in all_exports:
        lines.append(f'    "{name}",')
    lines.append("]")

    lines.append("")
    return "\n".join(lines)
